import Head from 'next/head'
import Link from 'next/link'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [state, setState] = useState({
    addRea: false,
    addCon: false,
  })
  const [rea, setRea] = useState({
    title: " ",
    reactant: " ",
    product: " ",
    reagent: " ",
    desc: " "
  })
  const [con, setCon] = useState({
    title: " ",
    desc: " "
  })
  const [reaArr, setReaArr] = useState([])
  const [conArr, setConArr] = useState([])

  // Note: the empty deps array [] means
  // this useEffect will run once
  // similar to componentDidMount()
  useEffect(() => {
    setReaArr([...JSON.parse(localStorage.getItem("reactions"))])
    setConArr([...JSON.parse(localStorage.getItem("concepts"))])
  }, [])

  const handleChange = (type, name) => {
    if (type === "rea") {
      setRea((prevState) => ({
        ...prevState,
        [name]: event.target.value,
      }))
    } else {
      setCon((prevState) => ({
        ...prevState,
        [name]: event.target.value,
      }))
    }
    console.log(rea)
    console.log(con)
  }
  const handleReaAdd = () => {
    console.log("hello")
    setReaArr((prevState)=>{
      localStorage.setItem("reactions", JSON.stringify([...prevState, rea]))
      return [...prevState, rea]
    })
    setRea({
      title: " ",
      reactant: " ",
      product: " ",
      reagent: " ",
      desc: " "
    })
    event.preventDefault();
  }
  const handleConcAdd = () => {
    console.log("hello")
    setConArr((prevState) => {
      localStorage.setItem("concepts", JSON.stringify([...prevState, con]))
      return [...prevState, con]
    })
    setCon({
      title: " ",
      desc: " "
    })
    event.preventDefault();
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Chem<span className={styles.blue}>Gyi</span>
        </h1>
        <div>
          <p className={styles.btns}>
            <button onClick={() => {
              setState({
                addRea: true,
                addCon: false
              })
            }}>Add Reaction</button>
            <button onClick={() => {
              setState({
                addRea: false,
                addCon: true
              })
            }}>Add Concept</button>
          </p>
          {state.addRea ? (
            <form onSubmit={handleReaAdd} className={styles.addRxn}>
              <label htmlFor="title">Enter the Title:</label>
              <input type="text" name="title" id="title" value={rea.title} onChange={() => handleChange("rea", "title")} />
              <label htmlFor="from">Enter the Reactant:</label>
              <input type="text" name="from" id="from" value={rea.reactant} onChange={() => handleChange("rea", "reactant")} />
              <label htmlFor="to">Enter the Product:</label>
              <input type="text" name="to" id="to" value={rea.reagent} onChange={() => handleChange("rea", "reagent")} />
              <label htmlFor="reagent">Enter the Reagent:</label>
              <input type="text" name="reagent" id="reagent" value={rea.product} onChange={() => handleChange("rea", "product")} />
              <textarea name="desc" rows="10" cols="30" placeholder="Some Additional Info. Eg: Heat?, Sunlight?" value={rea.desc} onChange={() => handleChange("rea", "desc")}>
              </textarea>
              <button type="submit">Add</button>
            </form>
          ) : ""}
          {state.addCon ? (
            <form onSubmit={handleConcAdd} className={styles.addCon}>
              <label htmlFor="title">Enter the Title:</label>
              <input type="text" name="title" id="title" value={con.title} onChange={() => handleChange("con", "title")} />
              <textarea name="desc" rows="10" cols="30" placeholder="Explain the topic briefly" value={con.desc} onChange={() => handleChange("con", "desc")}>
              </textarea>
              <button type="submit">Add</button>
            </form>
          ) : ""}
          <div className={styles.grid}>
            <Link href="/reactions" className={styles.card}>
              <h2>Reactions &rarr;</h2>
            </Link>
            <Link href="/concepts" className={styles.card}>
              <h2>Concepts &rarr;</h2>
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}
